### PR TITLE
Add support for Scala 2.13.0-M5

### PR DESCRIPTION
**Pull request by julienrf**
This PR is based on #5, it addresses the reviewers feedback and then adds support for M5.

Fixes nbronson/scala-stm#69

### CODE REVIEW

**Comment by Sciss** [comment]
Hah, you were faster than me typing in the previous PR. Thanks for the new PR.

Just one more question for clarification: so `mapInPlace` has been removed from `MapOps` in M5, correct? So only `filterInPlace` and `mapValuesInPlace` need to be overriden?

**Comment by julienrf** [comment]
> Just one more question for clarification: so `mapInPlace` has been removed from `MapOps` in M5, correct? So only `filterInPlace` and `mapValuesInPlace` need to be overriden?

Correct!

`mapInPlace` only exists in `mutable.IndexedSeqOps`.

**Comment by julienrf** [comment]
The CI is green but I saw several stack traces in the logs, is that expected?

**Comment by Sciss** [comment]
I also had these in previous builds; seems some scalatest thing is not correctly initialising or cleaning-up. I suspect it's https://github.com/scalatest/scalatest/issues/556

Given that the tests report success nevertheless, I will then merge and close. All good, thanks!

**Comment by Sciss** [comment]
scala-stm 0.9 is now published for Scala 2.11, 2.12, 2.13.0-M5 to maven central

**Comment by SethTisue** [comment]
scala/make-release-notes@a97f7fd451741157cf890cf8fe2c9aa851f1d580

**Pull request merged**
